### ISSUE TITLE
Add meta data

### ISSUE THREAD

**Issue by JSlote** [CarletonDevX/textbook-exchange#152]
- [x] Description for Google
- [x] Description for Facebook
- [x] Add image for Facebook
- [x] Add image non-relative paths
